"""HackAZ - Rating

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cJA_KCyjBSdnzfI3nb-2PCwmlFF80H_t#scrollTo=RvbB43Eduyrn
"""

import nltk
from difflib import SequenceMatcher

def hello_world(request):
    """Responds to any HTTP request.
    Args:
        request (flask.Request): HTTP request object.
    Returns:
        The response text or any set of values that can be turned into a
        Response object using
        `make_response <http://flask.pocoo.org/docs/1.0/api/#flask.Flask.make_response>`.
    """
#    request_json = request.get_json()
#    if request.args and 'message' in request.args:
#        return request.args.get('message')
#    elif request_json and 'message' in request_json:
#        return request_json['message']
    
    jobtext = "Python Developer duties and responsibilities Write reusable, testable, and efficient code Design and implement of low-latency, high-availability, and performant applications Integration of user-facing elements developed by front-end developers with server side logic Implementation of security and data protection Integration of data storage solutions Performance tuning, improvement, balancing, usability, automation Work collaboratively with design team to understand end user requirements to provide technical solutions and for the implementation of new software features"
    
    resume = "'skills': ['Javascript', 'Architecture', 'Usability', 'Reports', 'Wireframing', 'Communication', 'Statistics', 'Java', 'Matlab', 'Python', 'Forecasting', 'Queries', 'Computer science', 'Spark', 'Jupyter', 'Mining', 'Programming', 'Operating systems', 'Design', 'C++', 'Database', 'Ux', 'Technical', 'C', 'Php', 'Api', 'Datasets', 'Networking', 'Algorithms', 'Engineering', 'Html', 'Security', 'Android', 'Analysis', 'Cryptography', 'Excel', 'Scala', 'R', 'Sql'], 'college_name': None, 'degree': ['Master of Computer Science', 'Bachelor of Technology in Computer Science and Engineering'], 'designation': None, 'experience': ['help of maps and live location.', '• Conducted thorough competitor analysis, requirement and usability studies. Achieved a higher satisfaction rating.', 'Develop and Run Spatial Queries on Geo-databases', 'Guide: Mr. Jia Yu', 'Tempe, Arizona', 'Period: September 2019-December 2019', '• Extract data from a peer-to-peer taxi cab ﬁrm’s extensive database that contains geographic data as well as', 'real-time location data of customers, using Apache Spark and SparkSQL.', '• Developed and performed spatial hot spot analysis which includes hot zone analysis and hot cell analysis.', 'ACADEMIC ACHIEVEMENTS AND EXTRA-CURRICULAR ACTIVITIES', '• Awarded Scholarship from the Ministry of External Aﬀairs (Govt. of India) for academic performance', 'in the Higher secondary examination conducted by the Board.', '• Head of Media Relations Team of the National Level Inter-Collegiate Cultural Festival of NIT-Trichy', '(2016-2019). Associated with HBO, WB, Netﬂix, etc. Handled media aspects and led a team of 50 members.'], 'company_names': None, 'no_of_pages': 1, 'total_experience': 0.25}"
    
    
    def similar(a, b):
        return SequenceMatcher(None, a, b).ratio()
    
    print(similar(jobtext,resume))
    
    nltk.edit_distance(jobtext,resume)
    a1= set(jobtext)
    a2= set(resume)
    return nltk.jaccard_distance(a1,a2)
