"""HackAZ - Parser

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oO3D-2M6qcFiNBzTbTR_oVoT91u87wms
"""

import nltk
import spacy
nltk.download("stopwords")
from pyresparser import ResumeParser

def parse_resume(event, context):
    """Triggered by a change to a Cloud Storage bucket.
    Args:
         event (dict): Event payload.
         context (google.cloud.functions.Context): Metadata for the event.
    """
    nlp = spacy.load("en_core_web_sm")
    file = event
    print(f"Processing file: {file['name']}.")
    data = ResumeParser(file).get_extracted_data()
    print(f"Resume Data: {data}")
    return data
